/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransportRouteImport } from './routes/transport'
import { Route as TimetableRouteImport } from './routes/timetable'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SelectInstituteRouteImport } from './routes/select-institute'
import { Route as RolesRouteImport } from './routes/roles'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PayrollRouteImport } from './routes/payroll'
import { Route as ParentsRouteImport } from './routes/parents'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as HostelRouteImport } from './routes/hostel'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FeesRouteImport } from './routes/fees'
import { Route as ExamsRouteImport } from './routes/exams'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as CommunicationRouteImport } from './routes/communication'
import { Route as ClassesRouteImport } from './routes/classes'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as AssignmentsRouteImport } from './routes/assignments'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentsIndexRouteImport } from './routes/students.index'
import { Route as TeacherNoticesRouteImport } from './routes/teacher.notices'
import { Route as TeacherMaterialsRouteImport } from './routes/teacher.materials'
import { Route as TeacherMaintenanceRouteImport } from './routes/teacher.maintenance'
import { Route as TeacherLessonPlansRouteImport } from './routes/teacher.lesson-plans'
import { Route as TeacherLeaveRouteImport } from './routes/teacher.leave'
import { Route as TeacherDashboardRouteImport } from './routes/teacher.dashboard'
import { Route as TeacherClassesRouteImport } from './routes/teacher.classes'
import { Route as TeacherAttendanceRouteImport } from './routes/teacher.attendance'
import { Route as SuperUsersRouteImport } from './routes/super.users'
import { Route as SuperBillingRouteImport } from './routes/super.billing'
import { Route as SubjectsIdRouteImport } from './routes/subjects.$id'
import { Route as StudentsIdRouteImport } from './routes/students.$id'
import { Route as StudentWalletRouteImport } from './routes/student.wallet'
import { Route as StudentTimetableRouteImport } from './routes/student.timetable'
import { Route as StudentResultsRouteImport } from './routes/student.results'
import { Route as StudentNoticesRouteImport } from './routes/student.notices'
import { Route as StudentMaterialsRouteImport } from './routes/student.materials'
import { Route as StudentLibraryRouteImport } from './routes/student.library'
import { Route as StudentFeesRouteImport } from './routes/student.fees'
import { Route as StudentExamsRouteImport } from './routes/student.exams'
import { Route as StudentDashboardRouteImport } from './routes/student.dashboard'
import { Route as StudentAttendanceRouteImport } from './routes/student.attendance'
import { Route as StudentAssignmentsRouteImport } from './routes/student.assignments'
import { Route as ParentDashboardRouteImport } from './routes/parent.dashboard'
import { Route as ParentChildrenRouteImport } from './routes/parent.children'
import { Route as ExamsIdRouteImport } from './routes/exams.$id'
import { Route as ClassesIdRouteImport } from './routes/classes.$id'
import { Route as AssignmentsIdRouteImport } from './routes/assignments.$id'
import { Route as AdminStudentArchiveRouteImport } from './routes/admin.student-archive'
import { Route as AdminMaintenanceRouteImport } from './routes/admin.maintenance'
import { Route as AdminInfrastructureRouteImport } from './routes/admin.infrastructure'
import { Route as AdminIdCardsRouteImport } from './routes/admin.id-cards'
import { Route as AdminGatePassRouteImport } from './routes/admin.gate-pass'
import { Route as AdminFeeCollectionRouteImport } from './routes/admin.fee-collection'
import { Route as AdminExpensesRouteImport } from './routes/admin.expenses'
import { Route as AdminDmsRouteImport } from './routes/admin.dms'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminAssetsRouteImport } from './routes/admin.assets'
import { Route as AdminAdmissionsRouteImport } from './routes/admin.admissions'
import { Route as SuperInstitutesIndexRouteImport } from './routes/super.institutes.index'
import { Route as TeacherMaterialsIdRouteImport } from './routes/teacher.materials.$id'
import { Route as TeacherLessonPlansIdRouteImport } from './routes/teacher.lesson-plans.$id'
import { Route as SuperInstitutesNewRouteImport } from './routes/super.institutes.new'
import { Route as SuperInstitutesIdRouteImport } from './routes/super.institutes.$id'
import { Route as ParentChildrenIdRouteImport } from './routes/parent.children.$id'
import { Route as AdminAdmissionsIdRouteImport } from './routes/admin.admissions.$id'

const TransportRoute = TransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => rootRouteImport,
} as any)
const TimetableRoute = TimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectInstituteRoute = SelectInstituteRouteImport.update({
  id: '/select-institute',
  path: '/select-institute',
  getParentRoute: () => rootRouteImport,
} as any)
const RolesRoute = RolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollRoute = PayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsRoute = ParentsRouteImport.update({
  id: '/parents',
  path: '/parents',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const HostelRoute = HostelRouteImport.update({
  id: '/hostel',
  path: '/hostel',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FeesRoute = FeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsRoute = ExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunicationRoute = CommunicationRouteImport.update({
  id: '/communication',
  path: '/communication',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesRoute = ClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentsRoute = AssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsIndexRoute = StudentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentsRoute,
} as any)
const TeacherNoticesRoute = TeacherNoticesRouteImport.update({
  id: '/teacher/notices',
  path: '/teacher/notices',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherMaterialsRoute = TeacherMaterialsRouteImport.update({
  id: '/teacher/materials',
  path: '/teacher/materials',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherMaintenanceRoute = TeacherMaintenanceRouteImport.update({
  id: '/teacher/maintenance',
  path: '/teacher/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherLessonPlansRoute = TeacherLessonPlansRouteImport.update({
  id: '/teacher/lesson-plans',
  path: '/teacher/lesson-plans',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherLeaveRoute = TeacherLeaveRouteImport.update({
  id: '/teacher/leave',
  path: '/teacher/leave',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherDashboardRoute = TeacherDashboardRouteImport.update({
  id: '/teacher/dashboard',
  path: '/teacher/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherClassesRoute = TeacherClassesRouteImport.update({
  id: '/teacher/classes',
  path: '/teacher/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherAttendanceRoute = TeacherAttendanceRouteImport.update({
  id: '/teacher/attendance',
  path: '/teacher/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperUsersRoute = SuperUsersRouteImport.update({
  id: '/super/users',
  path: '/super/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperBillingRoute = SuperBillingRouteImport.update({
  id: '/super/billing',
  path: '/super/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsIdRoute = SubjectsIdRouteImport.update({
  id: '/subjects/$id',
  path: '/subjects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsIdRoute = StudentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StudentsRoute,
} as any)
const StudentWalletRoute = StudentWalletRouteImport.update({
  id: '/student/wallet',
  path: '/student/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentTimetableRoute = StudentTimetableRouteImport.update({
  id: '/student/timetable',
  path: '/student/timetable',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentResultsRoute = StudentResultsRouteImport.update({
  id: '/student/results',
  path: '/student/results',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentNoticesRoute = StudentNoticesRouteImport.update({
  id: '/student/notices',
  path: '/student/notices',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentMaterialsRoute = StudentMaterialsRouteImport.update({
  id: '/student/materials',
  path: '/student/materials',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentLibraryRoute = StudentLibraryRouteImport.update({
  id: '/student/library',
  path: '/student/library',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentFeesRoute = StudentFeesRouteImport.update({
  id: '/student/fees',
  path: '/student/fees',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentExamsRoute = StudentExamsRouteImport.update({
  id: '/student/exams',
  path: '/student/exams',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/student/dashboard',
  path: '/student/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentAttendanceRoute = StudentAttendanceRouteImport.update({
  id: '/student/attendance',
  path: '/student/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentAssignmentsRoute = StudentAssignmentsRouteImport.update({
  id: '/student/assignments',
  path: '/student/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentDashboardRoute = ParentDashboardRouteImport.update({
  id: '/parent/dashboard',
  path: '/parent/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentChildrenRoute = ParentChildrenRouteImport.update({
  id: '/parent/children',
  path: '/parent/children',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsIdRoute = ExamsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ExamsRoute,
} as any)
const ClassesIdRoute = ClassesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ClassesRoute,
} as any)
const AssignmentsIdRoute = AssignmentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AssignmentsRoute,
} as any)
const AdminStudentArchiveRoute = AdminStudentArchiveRouteImport.update({
  id: '/admin/student-archive',
  path: '/admin/student-archive',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMaintenanceRoute = AdminMaintenanceRouteImport.update({
  id: '/admin/maintenance',
  path: '/admin/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInfrastructureRoute = AdminInfrastructureRouteImport.update({
  id: '/admin/infrastructure',
  path: '/admin/infrastructure',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIdCardsRoute = AdminIdCardsRouteImport.update({
  id: '/admin/id-cards',
  path: '/admin/id-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGatePassRoute = AdminGatePassRouteImport.update({
  id: '/admin/gate-pass',
  path: '/admin/gate-pass',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFeeCollectionRoute = AdminFeeCollectionRouteImport.update({
  id: '/admin/fee-collection',
  path: '/admin/fee-collection',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminExpensesRoute = AdminExpensesRouteImport.update({
  id: '/admin/expenses',
  path: '/admin/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDmsRoute = AdminDmsRouteImport.update({
  id: '/admin/dms',
  path: '/admin/dms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAssetsRoute = AdminAssetsRouteImport.update({
  id: '/admin/assets',
  path: '/admin/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdmissionsRoute = AdminAdmissionsRouteImport.update({
  id: '/admin/admissions',
  path: '/admin/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperInstitutesIndexRoute = SuperInstitutesIndexRouteImport.update({
  id: '/super/institutes/',
  path: '/super/institutes/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherMaterialsIdRoute = TeacherMaterialsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TeacherMaterialsRoute,
} as any)
const TeacherLessonPlansIdRoute = TeacherLessonPlansIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TeacherLessonPlansRoute,
} as any)
const SuperInstitutesNewRoute = SuperInstitutesNewRouteImport.update({
  id: '/super/institutes/new',
  path: '/super/institutes/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperInstitutesIdRoute = SuperInstitutesIdRouteImport.update({
  id: '/super/institutes/$id',
  path: '/super/institutes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentChildrenIdRoute = ParentChildrenIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ParentChildrenRoute,
} as any)
const AdminAdmissionsIdRoute = AdminAdmissionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminAdmissionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/analytics': typeof AnalyticsRoute
  '/assignments': typeof AssignmentsRouteWithChildren
  '/attendance': typeof AttendanceRoute
  '/classes': typeof ClassesRouteWithChildren
  '/communication': typeof CommunicationRoute
  '/employees': typeof EmployeesRoute
  '/exams': typeof ExamsRouteWithChildren
  '/fees': typeof FeesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/hostel': typeof HostelRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/parents': typeof ParentsRoute
  '/payroll': typeof PayrollRoute
  '/profile': typeof ProfileRoute
  '/roles': typeof RolesRoute
  '/select-institute': typeof SelectInstituteRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/students': typeof StudentsRouteWithChildren
  '/timetable': typeof TimetableRoute
  '/transport': typeof TransportRoute
  '/admin/admissions': typeof AdminAdmissionsRouteWithChildren
  '/admin/assets': typeof AdminAssetsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/dms': typeof AdminDmsRoute
  '/admin/expenses': typeof AdminExpensesRoute
  '/admin/fee-collection': typeof AdminFeeCollectionRoute
  '/admin/gate-pass': typeof AdminGatePassRoute
  '/admin/id-cards': typeof AdminIdCardsRoute
  '/admin/infrastructure': typeof AdminInfrastructureRoute
  '/admin/maintenance': typeof AdminMaintenanceRoute
  '/admin/student-archive': typeof AdminStudentArchiveRoute
  '/assignments/$id': typeof AssignmentsIdRoute
  '/classes/$id': typeof ClassesIdRoute
  '/exams/$id': typeof ExamsIdRoute
  '/parent/children': typeof ParentChildrenRouteWithChildren
  '/parent/dashboard': typeof ParentDashboardRoute
  '/student/assignments': typeof StudentAssignmentsRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/exams': typeof StudentExamsRoute
  '/student/fees': typeof StudentFeesRoute
  '/student/library': typeof StudentLibraryRoute
  '/student/materials': typeof StudentMaterialsRoute
  '/student/notices': typeof StudentNoticesRoute
  '/student/results': typeof StudentResultsRoute
  '/student/timetable': typeof StudentTimetableRoute
  '/student/wallet': typeof StudentWalletRoute
  '/students/$id': typeof StudentsIdRoute
  '/subjects/$id': typeof SubjectsIdRoute
  '/super/billing': typeof SuperBillingRoute
  '/super/users': typeof SuperUsersRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/classes': typeof TeacherClassesRoute
  '/teacher/dashboard': typeof TeacherDashboardRoute
  '/teacher/leave': typeof TeacherLeaveRoute
  '/teacher/lesson-plans': typeof TeacherLessonPlansRouteWithChildren
  '/teacher/maintenance': typeof TeacherMaintenanceRoute
  '/teacher/materials': typeof TeacherMaterialsRouteWithChildren
  '/teacher/notices': typeof TeacherNoticesRoute
  '/students/': typeof StudentsIndexRoute
  '/admin/admissions/$id': typeof AdminAdmissionsIdRoute
  '/parent/children/$id': typeof ParentChildrenIdRoute
  '/super/institutes/$id': typeof SuperInstitutesIdRoute
  '/super/institutes/new': typeof SuperInstitutesNewRoute
  '/teacher/lesson-plans/$id': typeof TeacherLessonPlansIdRoute
  '/teacher/materials/$id': typeof TeacherMaterialsIdRoute
  '/super/institutes/': typeof SuperInstitutesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/analytics': typeof AnalyticsRoute
  '/assignments': typeof AssignmentsRouteWithChildren
  '/attendance': typeof AttendanceRoute
  '/classes': typeof ClassesRouteWithChildren
  '/communication': typeof CommunicationRoute
  '/employees': typeof EmployeesRoute
  '/exams': typeof ExamsRouteWithChildren
  '/fees': typeof FeesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/hostel': typeof HostelRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/parents': typeof ParentsRoute
  '/payroll': typeof PayrollRoute
  '/profile': typeof ProfileRoute
  '/roles': typeof RolesRoute
  '/select-institute': typeof SelectInstituteRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/timetable': typeof TimetableRoute
  '/transport': typeof TransportRoute
  '/admin/admissions': typeof AdminAdmissionsRouteWithChildren
  '/admin/assets': typeof AdminAssetsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/dms': typeof AdminDmsRoute
  '/admin/expenses': typeof AdminExpensesRoute
  '/admin/fee-collection': typeof AdminFeeCollectionRoute
  '/admin/gate-pass': typeof AdminGatePassRoute
  '/admin/id-cards': typeof AdminIdCardsRoute
  '/admin/infrastructure': typeof AdminInfrastructureRoute
  '/admin/maintenance': typeof AdminMaintenanceRoute
  '/admin/student-archive': typeof AdminStudentArchiveRoute
  '/assignments/$id': typeof AssignmentsIdRoute
  '/classes/$id': typeof ClassesIdRoute
  '/exams/$id': typeof ExamsIdRoute
  '/parent/children': typeof ParentChildrenRouteWithChildren
  '/parent/dashboard': typeof ParentDashboardRoute
  '/student/assignments': typeof StudentAssignmentsRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/exams': typeof StudentExamsRoute
  '/student/fees': typeof StudentFeesRoute
  '/student/library': typeof StudentLibraryRoute
  '/student/materials': typeof StudentMaterialsRoute
  '/student/notices': typeof StudentNoticesRoute
  '/student/results': typeof StudentResultsRoute
  '/student/timetable': typeof StudentTimetableRoute
  '/student/wallet': typeof StudentWalletRoute
  '/students/$id': typeof StudentsIdRoute
  '/subjects/$id': typeof SubjectsIdRoute
  '/super/billing': typeof SuperBillingRoute
  '/super/users': typeof SuperUsersRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/classes': typeof TeacherClassesRoute
  '/teacher/dashboard': typeof TeacherDashboardRoute
  '/teacher/leave': typeof TeacherLeaveRoute
  '/teacher/lesson-plans': typeof TeacherLessonPlansRouteWithChildren
  '/teacher/maintenance': typeof TeacherMaintenanceRoute
  '/teacher/materials': typeof TeacherMaterialsRouteWithChildren
  '/teacher/notices': typeof TeacherNoticesRoute
  '/students': typeof StudentsIndexRoute
  '/admin/admissions/$id': typeof AdminAdmissionsIdRoute
  '/parent/children/$id': typeof ParentChildrenIdRoute
  '/super/institutes/$id': typeof SuperInstitutesIdRoute
  '/super/institutes/new': typeof SuperInstitutesNewRoute
  '/teacher/lesson-plans/$id': typeof TeacherLessonPlansIdRoute
  '/teacher/materials/$id': typeof TeacherMaterialsIdRoute
  '/super/institutes': typeof SuperInstitutesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/analytics': typeof AnalyticsRoute
  '/assignments': typeof AssignmentsRouteWithChildren
  '/attendance': typeof AttendanceRoute
  '/classes': typeof ClassesRouteWithChildren
  '/communication': typeof CommunicationRoute
  '/employees': typeof EmployeesRoute
  '/exams': typeof ExamsRouteWithChildren
  '/fees': typeof FeesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/hostel': typeof HostelRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/parents': typeof ParentsRoute
  '/payroll': typeof PayrollRoute
  '/profile': typeof ProfileRoute
  '/roles': typeof RolesRoute
  '/select-institute': typeof SelectInstituteRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/students': typeof StudentsRouteWithChildren
  '/timetable': typeof TimetableRoute
  '/transport': typeof TransportRoute
  '/admin/admissions': typeof AdminAdmissionsRouteWithChildren
  '/admin/assets': typeof AdminAssetsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/dms': typeof AdminDmsRoute
  '/admin/expenses': typeof AdminExpensesRoute
  '/admin/fee-collection': typeof AdminFeeCollectionRoute
  '/admin/gate-pass': typeof AdminGatePassRoute
  '/admin/id-cards': typeof AdminIdCardsRoute
  '/admin/infrastructure': typeof AdminInfrastructureRoute
  '/admin/maintenance': typeof AdminMaintenanceRoute
  '/admin/student-archive': typeof AdminStudentArchiveRoute
  '/assignments/$id': typeof AssignmentsIdRoute
  '/classes/$id': typeof ClassesIdRoute
  '/exams/$id': typeof ExamsIdRoute
  '/parent/children': typeof ParentChildrenRouteWithChildren
  '/parent/dashboard': typeof ParentDashboardRoute
  '/student/assignments': typeof StudentAssignmentsRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/exams': typeof StudentExamsRoute
  '/student/fees': typeof StudentFeesRoute
  '/student/library': typeof StudentLibraryRoute
  '/student/materials': typeof StudentMaterialsRoute
  '/student/notices': typeof StudentNoticesRoute
  '/student/results': typeof StudentResultsRoute
  '/student/timetable': typeof StudentTimetableRoute
  '/student/wallet': typeof StudentWalletRoute
  '/students/$id': typeof StudentsIdRoute
  '/subjects/$id': typeof SubjectsIdRoute
  '/super/billing': typeof SuperBillingRoute
  '/super/users': typeof SuperUsersRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/classes': typeof TeacherClassesRoute
  '/teacher/dashboard': typeof TeacherDashboardRoute
  '/teacher/leave': typeof TeacherLeaveRoute
  '/teacher/lesson-plans': typeof TeacherLessonPlansRouteWithChildren
  '/teacher/maintenance': typeof TeacherMaintenanceRoute
  '/teacher/materials': typeof TeacherMaterialsRouteWithChildren
  '/teacher/notices': typeof TeacherNoticesRoute
  '/students/': typeof StudentsIndexRoute
  '/admin/admissions/$id': typeof AdminAdmissionsIdRoute
  '/parent/children/$id': typeof ParentChildrenIdRoute
  '/super/institutes/$id': typeof SuperInstitutesIdRoute
  '/super/institutes/new': typeof SuperInstitutesNewRoute
  '/teacher/lesson-plans/$id': typeof TeacherLessonPlansIdRoute
  '/teacher/materials/$id': typeof TeacherMaterialsIdRoute
  '/super/institutes/': typeof SuperInstitutesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/analytics'
    | '/assignments'
    | '/attendance'
    | '/classes'
    | '/communication'
    | '/employees'
    | '/exams'
    | '/fees'
    | '/forgot-password'
    | '/hostel'
    | '/library'
    | '/login'
    | '/notifications'
    | '/parents'
    | '/payroll'
    | '/profile'
    | '/roles'
    | '/select-institute'
    | '/settings'
    | '/signup'
    | '/students'
    | '/timetable'
    | '/transport'
    | '/admin/admissions'
    | '/admin/assets'
    | '/admin/audit'
    | '/admin/dms'
    | '/admin/expenses'
    | '/admin/fee-collection'
    | '/admin/gate-pass'
    | '/admin/id-cards'
    | '/admin/infrastructure'
    | '/admin/maintenance'
    | '/admin/student-archive'
    | '/assignments/$id'
    | '/classes/$id'
    | '/exams/$id'
    | '/parent/children'
    | '/parent/dashboard'
    | '/student/assignments'
    | '/student/attendance'
    | '/student/dashboard'
    | '/student/exams'
    | '/student/fees'
    | '/student/library'
    | '/student/materials'
    | '/student/notices'
    | '/student/results'
    | '/student/timetable'
    | '/student/wallet'
    | '/students/$id'
    | '/subjects/$id'
    | '/super/billing'
    | '/super/users'
    | '/teacher/attendance'
    | '/teacher/classes'
    | '/teacher/dashboard'
    | '/teacher/leave'
    | '/teacher/lesson-plans'
    | '/teacher/maintenance'
    | '/teacher/materials'
    | '/teacher/notices'
    | '/students/'
    | '/admin/admissions/$id'
    | '/parent/children/$id'
    | '/super/institutes/$id'
    | '/super/institutes/new'
    | '/teacher/lesson-plans/$id'
    | '/teacher/materials/$id'
    | '/super/institutes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/analytics'
    | '/assignments'
    | '/attendance'
    | '/classes'
    | '/communication'
    | '/employees'
    | '/exams'
    | '/fees'
    | '/forgot-password'
    | '/hostel'
    | '/library'
    | '/login'
    | '/notifications'
    | '/parents'
    | '/payroll'
    | '/profile'
    | '/roles'
    | '/select-institute'
    | '/settings'
    | '/signup'
    | '/timetable'
    | '/transport'
    | '/admin/admissions'
    | '/admin/assets'
    | '/admin/audit'
    | '/admin/dms'
    | '/admin/expenses'
    | '/admin/fee-collection'
    | '/admin/gate-pass'
    | '/admin/id-cards'
    | '/admin/infrastructure'
    | '/admin/maintenance'
    | '/admin/student-archive'
    | '/assignments/$id'
    | '/classes/$id'
    | '/exams/$id'
    | '/parent/children'
    | '/parent/dashboard'
    | '/student/assignments'
    | '/student/attendance'
    | '/student/dashboard'
    | '/student/exams'
    | '/student/fees'
    | '/student/library'
    | '/student/materials'
    | '/student/notices'
    | '/student/results'
    | '/student/timetable'
    | '/student/wallet'
    | '/students/$id'
    | '/subjects/$id'
    | '/super/billing'
    | '/super/users'
    | '/teacher/attendance'
    | '/teacher/classes'
    | '/teacher/dashboard'
    | '/teacher/leave'
    | '/teacher/lesson-plans'
    | '/teacher/maintenance'
    | '/teacher/materials'
    | '/teacher/notices'
    | '/students'
    | '/admin/admissions/$id'
    | '/parent/children/$id'
    | '/super/institutes/$id'
    | '/super/institutes/new'
    | '/teacher/lesson-plans/$id'
    | '/teacher/materials/$id'
    | '/super/institutes'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/analytics'
    | '/assignments'
    | '/attendance'
    | '/classes'
    | '/communication'
    | '/employees'
    | '/exams'
    | '/fees'
    | '/forgot-password'
    | '/hostel'
    | '/library'
    | '/login'
    | '/notifications'
    | '/parents'
    | '/payroll'
    | '/profile'
    | '/roles'
    | '/select-institute'
    | '/settings'
    | '/signup'
    | '/students'
    | '/timetable'
    | '/transport'
    | '/admin/admissions'
    | '/admin/assets'
    | '/admin/audit'
    | '/admin/dms'
    | '/admin/expenses'
    | '/admin/fee-collection'
    | '/admin/gate-pass'
    | '/admin/id-cards'
    | '/admin/infrastructure'
    | '/admin/maintenance'
    | '/admin/student-archive'
    | '/assignments/$id'
    | '/classes/$id'
    | '/exams/$id'
    | '/parent/children'
    | '/parent/dashboard'
    | '/student/assignments'
    | '/student/attendance'
    | '/student/dashboard'
    | '/student/exams'
    | '/student/fees'
    | '/student/library'
    | '/student/materials'
    | '/student/notices'
    | '/student/results'
    | '/student/timetable'
    | '/student/wallet'
    | '/students/$id'
    | '/subjects/$id'
    | '/super/billing'
    | '/super/users'
    | '/teacher/attendance'
    | '/teacher/classes'
    | '/teacher/dashboard'
    | '/teacher/leave'
    | '/teacher/lesson-plans'
    | '/teacher/maintenance'
    | '/teacher/materials'
    | '/teacher/notices'
    | '/students/'
    | '/admin/admissions/$id'
    | '/parent/children/$id'
    | '/super/institutes/$id'
    | '/super/institutes/new'
    | '/teacher/lesson-plans/$id'
    | '/teacher/materials/$id'
    | '/super/institutes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AssignmentsRoute: typeof AssignmentsRouteWithChildren
  AttendanceRoute: typeof AttendanceRoute
  ClassesRoute: typeof ClassesRouteWithChildren
  CommunicationRoute: typeof CommunicationRoute
  EmployeesRoute: typeof EmployeesRoute
  ExamsRoute: typeof ExamsRouteWithChildren
  FeesRoute: typeof FeesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HostelRoute: typeof HostelRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  ParentsRoute: typeof ParentsRoute
  PayrollRoute: typeof PayrollRoute
  ProfileRoute: typeof ProfileRoute
  RolesRoute: typeof RolesRoute
  SelectInstituteRoute: typeof SelectInstituteRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  StudentsRoute: typeof StudentsRouteWithChildren
  TimetableRoute: typeof TimetableRoute
  TransportRoute: typeof TransportRoute
  AdminAdmissionsRoute: typeof AdminAdmissionsRouteWithChildren
  AdminAssetsRoute: typeof AdminAssetsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminDmsRoute: typeof AdminDmsRoute
  AdminExpensesRoute: typeof AdminExpensesRoute
  AdminFeeCollectionRoute: typeof AdminFeeCollectionRoute
  AdminGatePassRoute: typeof AdminGatePassRoute
  AdminIdCardsRoute: typeof AdminIdCardsRoute
  AdminInfrastructureRoute: typeof AdminInfrastructureRoute
  AdminMaintenanceRoute: typeof AdminMaintenanceRoute
  AdminStudentArchiveRoute: typeof AdminStudentArchiveRoute
  ParentChildrenRoute: typeof ParentChildrenRouteWithChildren
  ParentDashboardRoute: typeof ParentDashboardRoute
  StudentAssignmentsRoute: typeof StudentAssignmentsRoute
  StudentAttendanceRoute: typeof StudentAttendanceRoute
  StudentDashboardRoute: typeof StudentDashboardRoute
  StudentExamsRoute: typeof StudentExamsRoute
  StudentFeesRoute: typeof StudentFeesRoute
  StudentLibraryRoute: typeof StudentLibraryRoute
  StudentMaterialsRoute: typeof StudentMaterialsRoute
  StudentNoticesRoute: typeof StudentNoticesRoute
  StudentResultsRoute: typeof StudentResultsRoute
  StudentTimetableRoute: typeof StudentTimetableRoute
  StudentWalletRoute: typeof StudentWalletRoute
  SubjectsIdRoute: typeof SubjectsIdRoute
  SuperBillingRoute: typeof SuperBillingRoute
  SuperUsersRoute: typeof SuperUsersRoute
  TeacherAttendanceRoute: typeof TeacherAttendanceRoute
  TeacherClassesRoute: typeof TeacherClassesRoute
  TeacherDashboardRoute: typeof TeacherDashboardRoute
  TeacherLeaveRoute: typeof TeacherLeaveRoute
  TeacherLessonPlansRoute: typeof TeacherLessonPlansRouteWithChildren
  TeacherMaintenanceRoute: typeof TeacherMaintenanceRoute
  TeacherMaterialsRoute: typeof TeacherMaterialsRouteWithChildren
  TeacherNoticesRoute: typeof TeacherNoticesRoute
  SuperInstitutesIdRoute: typeof SuperInstitutesIdRoute
  SuperInstitutesNewRoute: typeof SuperInstitutesNewRoute
  SuperInstitutesIndexRoute: typeof SuperInstitutesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transport': {
      id: '/transport'
      path: '/transport'
      fullPath: '/transport'
      preLoaderRoute: typeof TransportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timetable': {
      id: '/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof TimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-institute': {
      id: '/select-institute'
      path: '/select-institute'
      fullPath: '/select-institute'
      preLoaderRoute: typeof SelectInstituteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roles': {
      id: '/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof RolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll': {
      id: '/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof PayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents': {
      id: '/parents'
      path: '/parents'
      fullPath: '/parents'
      preLoaderRoute: typeof ParentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hostel': {
      id: '/hostel'
      path: '/hostel'
      fullPath: '/hostel'
      preLoaderRoute: typeof HostelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fees': {
      id: '/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof FeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams': {
      id: '/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof ExamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communication': {
      id: '/communication'
      path: '/communication'
      fullPath: '/communication'
      preLoaderRoute: typeof CommunicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes': {
      id: '/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof ClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignments': {
      id: '/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/': {
      id: '/students/'
      path: '/'
      fullPath: '/students/'
      preLoaderRoute: typeof StudentsIndexRouteImport
      parentRoute: typeof StudentsRoute
    }
    '/teacher/notices': {
      id: '/teacher/notices'
      path: '/teacher/notices'
      fullPath: '/teacher/notices'
      preLoaderRoute: typeof TeacherNoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/materials': {
      id: '/teacher/materials'
      path: '/teacher/materials'
      fullPath: '/teacher/materials'
      preLoaderRoute: typeof TeacherMaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/maintenance': {
      id: '/teacher/maintenance'
      path: '/teacher/maintenance'
      fullPath: '/teacher/maintenance'
      preLoaderRoute: typeof TeacherMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/lesson-plans': {
      id: '/teacher/lesson-plans'
      path: '/teacher/lesson-plans'
      fullPath: '/teacher/lesson-plans'
      preLoaderRoute: typeof TeacherLessonPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/leave': {
      id: '/teacher/leave'
      path: '/teacher/leave'
      fullPath: '/teacher/leave'
      preLoaderRoute: typeof TeacherLeaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/dashboard': {
      id: '/teacher/dashboard'
      path: '/teacher/dashboard'
      fullPath: '/teacher/dashboard'
      preLoaderRoute: typeof TeacherDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/classes': {
      id: '/teacher/classes'
      path: '/teacher/classes'
      fullPath: '/teacher/classes'
      preLoaderRoute: typeof TeacherClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/attendance': {
      id: '/teacher/attendance'
      path: '/teacher/attendance'
      fullPath: '/teacher/attendance'
      preLoaderRoute: typeof TeacherAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super/users': {
      id: '/super/users'
      path: '/super/users'
      fullPath: '/super/users'
      preLoaderRoute: typeof SuperUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super/billing': {
      id: '/super/billing'
      path: '/super/billing'
      fullPath: '/super/billing'
      preLoaderRoute: typeof SuperBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/$id': {
      id: '/subjects/$id'
      path: '/subjects/$id'
      fullPath: '/subjects/$id'
      preLoaderRoute: typeof SubjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/$id': {
      id: '/students/$id'
      path: '/$id'
      fullPath: '/students/$id'
      preLoaderRoute: typeof StudentsIdRouteImport
      parentRoute: typeof StudentsRoute
    }
    '/student/wallet': {
      id: '/student/wallet'
      path: '/student/wallet'
      fullPath: '/student/wallet'
      preLoaderRoute: typeof StudentWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/timetable': {
      id: '/student/timetable'
      path: '/student/timetable'
      fullPath: '/student/timetable'
      preLoaderRoute: typeof StudentTimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/results': {
      id: '/student/results'
      path: '/student/results'
      fullPath: '/student/results'
      preLoaderRoute: typeof StudentResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/notices': {
      id: '/student/notices'
      path: '/student/notices'
      fullPath: '/student/notices'
      preLoaderRoute: typeof StudentNoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/materials': {
      id: '/student/materials'
      path: '/student/materials'
      fullPath: '/student/materials'
      preLoaderRoute: typeof StudentMaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/library': {
      id: '/student/library'
      path: '/student/library'
      fullPath: '/student/library'
      preLoaderRoute: typeof StudentLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/fees': {
      id: '/student/fees'
      path: '/student/fees'
      fullPath: '/student/fees'
      preLoaderRoute: typeof StudentFeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/exams': {
      id: '/student/exams'
      path: '/student/exams'
      fullPath: '/student/exams'
      preLoaderRoute: typeof StudentExamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/student/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/attendance': {
      id: '/student/attendance'
      path: '/student/attendance'
      fullPath: '/student/attendance'
      preLoaderRoute: typeof StudentAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/assignments': {
      id: '/student/assignments'
      path: '/student/assignments'
      fullPath: '/student/assignments'
      preLoaderRoute: typeof StudentAssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/dashboard': {
      id: '/parent/dashboard'
      path: '/parent/dashboard'
      fullPath: '/parent/dashboard'
      preLoaderRoute: typeof ParentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/children': {
      id: '/parent/children'
      path: '/parent/children'
      fullPath: '/parent/children'
      preLoaderRoute: typeof ParentChildrenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams/$id': {
      id: '/exams/$id'
      path: '/$id'
      fullPath: '/exams/$id'
      preLoaderRoute: typeof ExamsIdRouteImport
      parentRoute: typeof ExamsRoute
    }
    '/classes/$id': {
      id: '/classes/$id'
      path: '/$id'
      fullPath: '/classes/$id'
      preLoaderRoute: typeof ClassesIdRouteImport
      parentRoute: typeof ClassesRoute
    }
    '/assignments/$id': {
      id: '/assignments/$id'
      path: '/$id'
      fullPath: '/assignments/$id'
      preLoaderRoute: typeof AssignmentsIdRouteImport
      parentRoute: typeof AssignmentsRoute
    }
    '/admin/student-archive': {
      id: '/admin/student-archive'
      path: '/admin/student-archive'
      fullPath: '/admin/student-archive'
      preLoaderRoute: typeof AdminStudentArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/maintenance': {
      id: '/admin/maintenance'
      path: '/admin/maintenance'
      fullPath: '/admin/maintenance'
      preLoaderRoute: typeof AdminMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/infrastructure': {
      id: '/admin/infrastructure'
      path: '/admin/infrastructure'
      fullPath: '/admin/infrastructure'
      preLoaderRoute: typeof AdminInfrastructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/id-cards': {
      id: '/admin/id-cards'
      path: '/admin/id-cards'
      fullPath: '/admin/id-cards'
      preLoaderRoute: typeof AdminIdCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/gate-pass': {
      id: '/admin/gate-pass'
      path: '/admin/gate-pass'
      fullPath: '/admin/gate-pass'
      preLoaderRoute: typeof AdminGatePassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/fee-collection': {
      id: '/admin/fee-collection'
      path: '/admin/fee-collection'
      fullPath: '/admin/fee-collection'
      preLoaderRoute: typeof AdminFeeCollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/expenses': {
      id: '/admin/expenses'
      path: '/admin/expenses'
      fullPath: '/admin/expenses'
      preLoaderRoute: typeof AdminExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dms': {
      id: '/admin/dms'
      path: '/admin/dms'
      fullPath: '/admin/dms'
      preLoaderRoute: typeof AdminDmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/assets': {
      id: '/admin/assets'
      path: '/admin/assets'
      fullPath: '/admin/assets'
      preLoaderRoute: typeof AdminAssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/admissions': {
      id: '/admin/admissions'
      path: '/admin/admissions'
      fullPath: '/admin/admissions'
      preLoaderRoute: typeof AdminAdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super/institutes/': {
      id: '/super/institutes/'
      path: '/super/institutes'
      fullPath: '/super/institutes/'
      preLoaderRoute: typeof SuperInstitutesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/materials/$id': {
      id: '/teacher/materials/$id'
      path: '/$id'
      fullPath: '/teacher/materials/$id'
      preLoaderRoute: typeof TeacherMaterialsIdRouteImport
      parentRoute: typeof TeacherMaterialsRoute
    }
    '/teacher/lesson-plans/$id': {
      id: '/teacher/lesson-plans/$id'
      path: '/$id'
      fullPath: '/teacher/lesson-plans/$id'
      preLoaderRoute: typeof TeacherLessonPlansIdRouteImport
      parentRoute: typeof TeacherLessonPlansRoute
    }
    '/super/institutes/new': {
      id: '/super/institutes/new'
      path: '/super/institutes/new'
      fullPath: '/super/institutes/new'
      preLoaderRoute: typeof SuperInstitutesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super/institutes/$id': {
      id: '/super/institutes/$id'
      path: '/super/institutes/$id'
      fullPath: '/super/institutes/$id'
      preLoaderRoute: typeof SuperInstitutesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/children/$id': {
      id: '/parent/children/$id'
      path: '/$id'
      fullPath: '/parent/children/$id'
      preLoaderRoute: typeof ParentChildrenIdRouteImport
      parentRoute: typeof ParentChildrenRoute
    }
    '/admin/admissions/$id': {
      id: '/admin/admissions/$id'
      path: '/$id'
      fullPath: '/admin/admissions/$id'
      preLoaderRoute: typeof AdminAdmissionsIdRouteImport
      parentRoute: typeof AdminAdmissionsRoute
    }
  }
}

interface AssignmentsRouteChildren {
  AssignmentsIdRoute: typeof AssignmentsIdRoute
}

const AssignmentsRouteChildren: AssignmentsRouteChildren = {
  AssignmentsIdRoute: AssignmentsIdRoute,
}

const AssignmentsRouteWithChildren = AssignmentsRoute._addFileChildren(
  AssignmentsRouteChildren,
)

interface ClassesRouteChildren {
  ClassesIdRoute: typeof ClassesIdRoute
}

const ClassesRouteChildren: ClassesRouteChildren = {
  ClassesIdRoute: ClassesIdRoute,
}

const ClassesRouteWithChildren =
  ClassesRoute._addFileChildren(ClassesRouteChildren)

interface ExamsRouteChildren {
  ExamsIdRoute: typeof ExamsIdRoute
}

const ExamsRouteChildren: ExamsRouteChildren = {
  ExamsIdRoute: ExamsIdRoute,
}

const ExamsRouteWithChildren = ExamsRoute._addFileChildren(ExamsRouteChildren)

interface StudentsRouteChildren {
  StudentsIdRoute: typeof StudentsIdRoute
  StudentsIndexRoute: typeof StudentsIndexRoute
}

const StudentsRouteChildren: StudentsRouteChildren = {
  StudentsIdRoute: StudentsIdRoute,
  StudentsIndexRoute: StudentsIndexRoute,
}

const StudentsRouteWithChildren = StudentsRoute._addFileChildren(
  StudentsRouteChildren,
)

interface AdminAdmissionsRouteChildren {
  AdminAdmissionsIdRoute: typeof AdminAdmissionsIdRoute
}

const AdminAdmissionsRouteChildren: AdminAdmissionsRouteChildren = {
  AdminAdmissionsIdRoute: AdminAdmissionsIdRoute,
}

const AdminAdmissionsRouteWithChildren = AdminAdmissionsRoute._addFileChildren(
  AdminAdmissionsRouteChildren,
)

interface ParentChildrenRouteChildren {
  ParentChildrenIdRoute: typeof ParentChildrenIdRoute
}

const ParentChildrenRouteChildren: ParentChildrenRouteChildren = {
  ParentChildrenIdRoute: ParentChildrenIdRoute,
}

const ParentChildrenRouteWithChildren = ParentChildrenRoute._addFileChildren(
  ParentChildrenRouteChildren,
)

interface TeacherLessonPlansRouteChildren {
  TeacherLessonPlansIdRoute: typeof TeacherLessonPlansIdRoute
}

const TeacherLessonPlansRouteChildren: TeacherLessonPlansRouteChildren = {
  TeacherLessonPlansIdRoute: TeacherLessonPlansIdRoute,
}

const TeacherLessonPlansRouteWithChildren =
  TeacherLessonPlansRoute._addFileChildren(TeacherLessonPlansRouteChildren)

interface TeacherMaterialsRouteChildren {
  TeacherMaterialsIdRoute: typeof TeacherMaterialsIdRoute
}

const TeacherMaterialsRouteChildren: TeacherMaterialsRouteChildren = {
  TeacherMaterialsIdRoute: TeacherMaterialsIdRoute,
}

const TeacherMaterialsRouteWithChildren =
  TeacherMaterialsRoute._addFileChildren(TeacherMaterialsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AnalyticsRoute: AnalyticsRoute,
  AssignmentsRoute: AssignmentsRouteWithChildren,
  AttendanceRoute: AttendanceRoute,
  ClassesRoute: ClassesRouteWithChildren,
  CommunicationRoute: CommunicationRoute,
  EmployeesRoute: EmployeesRoute,
  ExamsRoute: ExamsRouteWithChildren,
  FeesRoute: FeesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HostelRoute: HostelRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  ParentsRoute: ParentsRoute,
  PayrollRoute: PayrollRoute,
  ProfileRoute: ProfileRoute,
  RolesRoute: RolesRoute,
  SelectInstituteRoute: SelectInstituteRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  StudentsRoute: StudentsRouteWithChildren,
  TimetableRoute: TimetableRoute,
  TransportRoute: TransportRoute,
  AdminAdmissionsRoute: AdminAdmissionsRouteWithChildren,
  AdminAssetsRoute: AdminAssetsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminDmsRoute: AdminDmsRoute,
  AdminExpensesRoute: AdminExpensesRoute,
  AdminFeeCollectionRoute: AdminFeeCollectionRoute,
  AdminGatePassRoute: AdminGatePassRoute,
  AdminIdCardsRoute: AdminIdCardsRoute,
  AdminInfrastructureRoute: AdminInfrastructureRoute,
  AdminMaintenanceRoute: AdminMaintenanceRoute,
  AdminStudentArchiveRoute: AdminStudentArchiveRoute,
  ParentChildrenRoute: ParentChildrenRouteWithChildren,
  ParentDashboardRoute: ParentDashboardRoute,
  StudentAssignmentsRoute: StudentAssignmentsRoute,
  StudentAttendanceRoute: StudentAttendanceRoute,
  StudentDashboardRoute: StudentDashboardRoute,
  StudentExamsRoute: StudentExamsRoute,
  StudentFeesRoute: StudentFeesRoute,
  StudentLibraryRoute: StudentLibraryRoute,
  StudentMaterialsRoute: StudentMaterialsRoute,
  StudentNoticesRoute: StudentNoticesRoute,
  StudentResultsRoute: StudentResultsRoute,
  StudentTimetableRoute: StudentTimetableRoute,
  StudentWalletRoute: StudentWalletRoute,
  SubjectsIdRoute: SubjectsIdRoute,
  SuperBillingRoute: SuperBillingRoute,
  SuperUsersRoute: SuperUsersRoute,
  TeacherAttendanceRoute: TeacherAttendanceRoute,
  TeacherClassesRoute: TeacherClassesRoute,
  TeacherDashboardRoute: TeacherDashboardRoute,
  TeacherLeaveRoute: TeacherLeaveRoute,
  TeacherLessonPlansRoute: TeacherLessonPlansRouteWithChildren,
  TeacherMaintenanceRoute: TeacherMaintenanceRoute,
  TeacherMaterialsRoute: TeacherMaterialsRouteWithChildren,
  TeacherNoticesRoute: TeacherNoticesRoute,
  SuperInstitutesIdRoute: SuperInstitutesIdRoute,
  SuperInstitutesNewRoute: SuperInstitutesNewRoute,
  SuperInstitutesIndexRoute: SuperInstitutesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
